name: deploy

on: 
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: bwmmwb
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: cp -r dist /usr/share/nginx/html/bwmmwb
