name: deploy

on: 
  push:
    branches:
     - 'main'

jobs:
  checkout:
    runs-on: bwmmwb
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: rm -rf /usr/share/nginx/html/bwmmwb/*
      - run: cp -r dist/* /usr/share/nginx/html/bwmmwb
