name: deploy

on: workflow_dispatch

jobs:
  checkout:
    runs-on: bwmmwb
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: cp -r dist /usr/share/nginx/html/bwmmwb
